// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-school-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.105.2";
var supabaseForUser = (ctx) => {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) throw new Error("Missing Supabase MCP environment variables");
  return createClient(url, key, {
    global: {
      headers: {
        Authorization: `Bearer ${ctx.getToken()}`
      }
    },
    auth: {
      persistSession: false,
      autoRefreshToken: false
    }
  });
};
var get_school_overview_default = defineTool({
  name: "get_school_overview",
  title: "Get school overview",
  description: "Returns key attendance and registration totals from this app.",
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  inputSchema: {},
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    try {
      const supabase = supabaseForUser(ctx);
      const [registeredRes, presentRes, lateRes, gateSessionRes] = await Promise.all([
        supabase.from("attendance_records").select("id", { count: "exact", head: true }).eq("status", "registered"),
        supabase.from("attendance_records").select("id", { count: "exact", head: true }).eq("status", "present"),
        supabase.from("attendance_records").select("id", { count: "exact", head: true }).eq("status", "late"),
        supabase.from("gate_sessions").select("id, gate_name, started_at, ended_at").order("started_at", { ascending: false }).limit(1).maybeSingle()
      ]);
      const errors = [registeredRes.error, presentRes.error, lateRes.error, gateSessionRes.error].filter(Boolean);
      if (errors.length > 0) {
        return {
          content: [{ type: "text", text: `Query failed: ${errors.map((e) => e?.message).join("; ")}` }],
          isError: true
        };
      }
      const payload = {
        registered_students: registeredRes.count ?? 0,
        present_records: presentRes.count ?? 0,
        late_records: lateRes.count ?? 0,
        latest_gate_session: gateSessionRes.data ? {
          id: gateSessionRes.data.id,
          gate_name: gateSessionRes.data.gate_name,
          started_at: gateSessionRes.data.started_at,
          ended_at: gateSessionRes.data.ended_at
        } : null
      };
      return {
        content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
        structuredContent: payload
      };
    } catch (error) {
      return {
        content: [{ type: "text", text: error?.message || "Failed to fetch overview." }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/list-recent-gate-entries.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.2";
import { z } from "npm:zod@^4.1.13";
var supabaseForUser2 = (ctx) => {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  if (!url || !key) throw new Error("Missing Supabase MCP environment variables");
  return createClient2(url, key, {
    global: {
      headers: {
        Authorization: `Bearer ${ctx.getToken()}`
      }
    },
    auth: {
      persistSession: false,
      autoRefreshToken: false
    }
  });
};
var list_recent_gate_entries_default = defineTool2({
  name: "list_recent_gate_entries",
  title: "List recent gate entries",
  description: "Returns recent gate entry events with recognition status.",
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  inputSchema: {
    limit: z.number().optional().describe("How many recent gate entries to return (default 20).")
  },
  handler: async ({ limit = 20 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    try {
      const safeLimit = Math.max(1, Math.min(100, Math.floor(limit)));
      const supabase = supabaseForUser2(ctx);
      const { data, error } = await supabase.from("gate_entries").select("id, student_id, student_name, is_recognized, confidence_score, gate_name, entry_time, class, section").order("entry_time", { ascending: false }).limit(safeLimit);
      if (error) {
        return {
          content: [{ type: "text", text: `Query failed: ${error.message}` }],
          isError: true
        };
      }
      const rows = (data || []).map((row) => ({
        id: row.id,
        student_id: row.student_id,
        student_name: row.student_name,
        recognized: row.is_recognized,
        confidence: row.confidence_score,
        gate_name: row.gate_name,
        entry_time: row.entry_time,
        class: row.class,
        section: row.section
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
        structuredContent: { entries: rows }
      };
    } catch (error) {
      return {
        content: [{ type: "text", text: error?.message || "Failed to fetch gate entries." }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var projectRefFromUrl = (() => {
  const url = "https://mhiqslfnycfkalfqnkco.supabase.co";
  if (!url) return null;
  const match = url.match(/^https:\/\/([^.]+)\.supabase\.co/i);
  return match?.[1] || null;
})();
var projectRef = "mhiqslfnycfkalfqnkco";
var mcp_default = defineMcp({
  name: "presences-mcp",
  title: "Presences MCP",
  version: "0.1.0",
  instructions: "Use these tools to read school attendance summaries and recent gate entries from the Presences app for the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_school_overview_default, list_recent_gate_entries_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
